config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: "sessions"}
  mount Sidekiq::Web => "/sidekiq"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  post "inss/calculate"

  resources :proponents
  resources :dashboards, only: [:index]

  root "dashboards#index"
end

app/controllers/dashboards_controller.rb
# frozen_string_literal: true

class DashboardsController < ApplicationController
  def index
    @dashboard_list = ListPresenter.new(proponent_repository.grouped_by_salary_range)
  end

  private def proponent_repository
    @proponent_repository ||= ProponentRepository.new
  end
end

app/views/dashboards/index.html.erb
<div class="flex-column" style = "height: auto;">
  <h1> <%= t('.title') %> </h1>

  <table class="table table-striped">
    <ol class="fs-2">
      <thead class="table-secondary">
        <td class="text-center fw-bold"> <%= t('.header.salary_ranges') %> </td>
        <td class="text-center fw-bold"> <%= t('.header.quantity') %> </td>
      </thead>
      <% @dashboard_list.items.each do |salary_range, quantity| %>
        <tr class="record">
          <td class="text-center"><%= salary_range %> </td>
          <td class="text-center"><%= quantity %></td>
        </tr>
      <% end %>
    </ol>
  </table>
  <div class="row">
    <div class="col-md-6">
      <%= pie_chart @dashboard_list.items, id: 'dashboard-pie-chart' %>
    </div>
    <div class="col-md-6">
      <%= column_chart @dashboard_list.items, id: 'dashboard-column-chart' %>
    </div>
  </div>
  <%= link_to t('.buttons.proponents'), proponents_path, class: 'btn btn-secondary border-0 rounded-pill shadow p-3 m-3' %>
</div>