config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: "sessions"}
  mount Sidekiq::Web => "/sidekiq"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  post "inss/calculate"

  resources :proponents
  resources :dashboards, only: [:index]

  root "dashboards#index"
end

app/models/proponent.rb
# frozen_string_literal: true

# Proponent
#
# The `Proponent` model represents an poponent in the system.
# Proponents are individuals who provide information such as name,
# CPF (Brazilian social security number), birthday, and salary.
#
# Attributes:
# - `name`: The name of the proponent.
# - `cpf`: The CPF (unique) of the proponent.
# - `birthday`: The birthday of the proponent.
# - `salary`: The salary of the proponent.
# - `salary_liquid`: The salary liquid of the proponent.
# - `address`: The address(Address model) of the proponent.
#
# Usage Example:
# ```ruby
# proponent = Proponent.new(name: "John Doe", cpf: "123.456.789-09", birthday: Date.new(1980, 1, 1), salary: 5000.0)
# ```
#
# Validations:
# - `name`: Must be present.
# - `cpf`: Must be unique and present.
# - `birthday`: Must be a valid date.
# - `salary`: Can be a decimal number.
# - `salary liquid`: Can be a decimal number.
#
class Proponent < ApplicationRecord
  has_one :address, dependent: :destroy
  has_many :phones, dependent: :destroy

  encrypts :cpf, deterministic: true
  encrypts :salary, deterministic: true
  encrypts :salary_liquid, deterministic: true

  validates :name, presence: true
  validates :cpf, presence: true, uniqueness: true
  validates :salary, presence: true

  accepts_nested_attributes_for :phones

  scope :by_cpf, ->(cpf) { where cpf: }
end

app/controllers/proponents_controller.rb
# frozen_string_literal: true

# ProponentsController
#
# The ProponentsController handles the CRUD operations for proponents.
#
# Actions:
# - `index`: Display a paginated list of all proponents.
# - `show`: Display details of a specific proponent.
# - `new`: Render a form for creating a new proponent.
# - `create`: Create a new proponent based on form submissions.
# - `edit`: Render a form for editing an existing proponent.
# - `update`: Update an existing proponent based on form submissions.
# - `destroy`: destroy a proponent.
#
class ProponentsController < ApplicationController
  def index
    @proponent_list = ListPresenter.new(proponent_repository.fecth_paginated(page: params[:page]))
  end

  def show
    @proponent_presenter = ProponentPresenter.new(proponent)
  end

  def new
    @proponent_form = ProponentForm.new
  end

  def edit
    @proponent_form = ProponentForm.from(proponent)
  end

  def create
    @proponent_form = ProponentForm.new(proponent_form_attributes)
    create_proponent_response = CreateProponent.new(@proponent_form).create

    if create_proponent_response[:status] == :success
      redirect_to proponent_path(create_proponent_response[:proponent]),
                  notice: t("proponents.messages.create_successfully")
    else
      render :new
    end
  end

  def update
    @proponent_form = ProponentForm.new(proponent_form_attributes)
    update_proponent_response = UpdateProponent.new(@proponent_form).update

    if update_proponent_response[:status] == :success
      redirect_to proponents_path, notice: t("proponents.messages.update_successfully")
    else
      render :new
    end
  end

  def destroy
    destroy_proponent_response = DestroyProponent.new(params[:id]).destroy

    if destroy_proponent_response[:status] == :success
      redirect_to proponents_path, notice: t("proponents.messages.destroy_successfully")
    else
      redirect_to proponents_path, notice: t("proponents.messages.destroy_failure")
    end
  end

  private def proponent_repository
    @proponent_repository ||= ProponentRepository.new
  end

  private def proponent
    @proponent ||= proponent_repository.find(params[:id])
  end

  private def proponent_form_attributes
    {birthday: build_birthday}.merge proponent_form_params.except(
      "birthday(1i)", "birthday(2i)", "birthday(3i)"
    )
  end

  private def build_birthday
    year = params[:proponent_form]["birthday(1i)"].to_i
    month = params[:proponent_form]["birthday(2i)"].to_i
    day = params[:proponent_form]["birthday(3i)"].to_i

    Date.new(year, month, day)
  end

  private def proponent_form_params
    params.require(:proponent_form).permit(
      :id, :name, :cpf, :birthday, :salary, :inss,
      :street, :number, :district, :city, :state, :zip_code,
      personal: %i[area_code number phone_type],
      reference: %i[area_code number phone_type]
    )
  end
end

app/views/proponents/_form.html.erb
<%= simple_form_for proponent_form, url: path, html: { method: { new: :post, edit: :patch }[action] }, class: 'mt-4', data: { controller: 'proponent-form', turbo: false } do |form| %>
  <%= form.input :id, as: :hidden %>
  <div class="row mb-3">
    <div class="col">
      <%= form.input :name %>
    </div>
  </div>
  <div class="row mb-3">
    <div class="col-md-6">
      <%= form.input :cpf, input_html: { data: { 'proponent-form-target': "cpf" } } %>
    </div>
    <div class="col-md-6">
      <%= form.input :birthday, as: :date, start_year: Date.today.year - 90, end_year: Date.today.year - 18 %>
    </div>
  </div>
  <div class="row mb-3">
    <div class="col-md-6">
      <%= form.input :salary, input_html: { data: { action: "focusout->proponent-form#calculate", 'proponent-form-target': "salary" } } %>
    </div>
    <div class="col-md-6">
      <%= form.input :inss, input_html: { data: { 'proponent-form-target': "inss" }, readonly: true } %>
    </div>
  </div>
  <div class="row mb-3">
    <div class="col-md-6">
      <%= form.input :street %>
    </div>
    <div class="col-md-6">
      <%= form.input :number %>
    </div>
  </div>
  <div class="row mb-3">
    <div class="col-md-6">
      <%= form.input :district %>
    </div>
    <div class="col-md-6">
      <%= form.input :city %>
    </div>
  </div>
  <div class="row mb-3">
    <div class="col-md-6">
      <%= form.input :state %>
    </div>
    <div class="col-md-6">
      <%= form.input :zip_code, input_html: { data: { 'proponent-form-target': "zipCode" } } %>
    </div>
  </div>
  <div class="row mb-3">
    <%= render 'phone_form', form: form, type: :personal, value: proponent_form.personal %>
    <%= render 'phone_form', form: form, type: :reference, value: proponent_form.reference %>
    <% if proponent_form.errors[:phones].present? %>
      <p class="text-danger"><%= proponent_form.errors[:phones].first %></p>
    <% end %>
  </div>
  <div class="row mb-3">
    <div class="col-md-6">
      <%= form.submit t("proponents.#{action}.buttons.submit"), class: 'btn btn-primary' %>
      <%= link_to t("proponents.#{action}.buttons.back"), proponents_path, class: 'btn btn-secondary' %>
    </div>
  </div>
<% end %>

app/views/proponents/_phone_form.html.erb
<%= form.fields_for type, Phone.new(value) do |phone_form| %>
  <div class="row form-group">
    <div class="col-md-2">
      <%= phone_form.input :area_code %>
    </div>
    <div class="col-md-4">
      <%= phone_form.input :number %>
    </div>
    <div class="col-md-4">
      <%= phone_form.input :phone_type, as: :select, collection: Phone.phone_types.keys.map { |phone_type| [t("activerecord.attributes.phone.phone_types.#{phone_type}"), phone_type] }, include_blank: false, selected: type %>
    </div>
  </div>
<% end %>

app/views/proponents/edit.html.erb
<h1 class="display-4"><%= t('.title') %></h1>
<%= render 'form', proponent_form: @proponent_form, action: :edit, path: proponent_path(@proponent_form.id) %>

app/views/proponents/index.html.erb
<div class="flex-column" style = "height: auto;">
  <h1> <%= t('.title') %> </h1>
  <!--Error Message-->
  <% if flash[:errors] %>
    <% flash.each do |name,message| %>
      <p class="text-danger"><%= message%></p>
    <% end %>
  <% end %>
  <!-- Proponents Table -->
  <div>
    <table class="table table-striped">
      <ol class="fs-2">
        <thead class="table-secondary">
          <td class="text-center fw-bold"> <%= t('.header.name') %> </td>
          <td colspan=3 class="text-center fw-bold"> <%= t('.header.action') %> </td>
        </thead>
        <% if @proponent_list.items.size.positive? %>
          <% @proponent_list.items.each do |proponent| %>
            <tr class="record">
              <td class="text-center"><%= proponent.name %> </td>
              <td class="text-center"><%= button_to t('.table.buttons.show'), proponent_path(proponent), method: :get, class:"border-0 rounded-pill shadow px-3 py-2" %></td>
              <td class="text-center"><%= button_to t('.table.buttons.edit'), edit_proponent_path(proponent), method: :get, class:"border-0 rounded-pill shadow px-3 py-2" %></td>
              <td class="text-center"><%= button_to t('.table.buttons.destroy'), proponent, method: :delete, class:"btn btn-danger border-0 rounded-pill shadow px-3 py-2", data: { confirm: t('.table.confirm'), action: 'click->proponent-list#confirm', controller: 'proponent-list' } %></td>
            </tr>
          <% end %>
        <% else %>
          <tr>
            <td class="text-center" colspan="4"><%= t(".table.empty") %> </td>
          </tr>
        <% end %>
      </ol>
    </table>
    <%= paginate @proponent_list.items, theme: 'bootstrap-5' %>
  </div>
  <div class="d-flex">
    <%= button_to t('.buttons.create'), new_proponent_path, method: :get , class:"btn btn-primary border-0 rounded-pill shadow p-3 m-3" %>
    <%= link_to t('.buttons.dashboard'), dashboards_path, class:"btn btn-secondary border-0 rounded-pill shadow p-3 m-3" %>
  </div>
</div>

app/views/proponents/new.html.erb
<h1 class="display-4"><%= t('.title') %></h1>
<%= render 'form', proponent_form: @proponent_form, action: :new, path: proponents_path %>

app/views/proponents/show.html.erb
<div class="container mt-3" data-controller="proponent-presenter">
  <div class="row">
    <div class="col-md-6">
      <p><strong><%= t('activemodel.attributes.proponent_form.name')%>:</strong> <%= @proponent_presenter.name %></p>
      <p><strong><%= t('activemodel.attributes.proponent_form.cpf')%>:</strong> <%= @proponent_presenter.cpf %></p>
      <p><strong><%= t('activemodel.attributes.proponent_form.birthday')%>:</strong> <%= I18n.l(@proponent_presenter.birthday) %></p>
      <p><strong><%= t('activemodel.attributes.proponent_form.salary')%>:</strong> <span data-proponent-presenter-target="salary"><%= @proponent_presenter.salary %></span></span></p>
      <p><strong><%= t('activemodel.attributes.proponent_form.inss')%>:</strong> <span data-proponent-presenter-target="inss"><%= @proponent_presenter.inss %></span></span></p>
      <p><strong><%= t('activemodel.attributes.proponent_form.salary_liquid')%>:</strong> <span data-proponent-presenter-target="salaryLiquid"><%= @proponent_presenter.salary_liquid %></span></span></p>
    </div>

    <% if @proponent_presenter.street.present? %>
      <div class="col-md-6">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"><%= t('.labels.address') %></h5>
            <p class="card-text"><strong><%= t('activemodel.attributes.proponent_form.street')%>:</strong> <%= @proponent_presenter.street %></p>
            <p class="card-text"><strong><%= t('activemodel.attributes.proponent_form.number')%>:</strong> <%= @proponent_presenter.number %></p>
            <p class="card-text"><strong><%= t('activemodel.attributes.proponent_form.district')%>:</strong> <%= @proponent_presenter.district %></p>
            <p class="card-text"><strong><%= t('activemodel.attributes.proponent_form.city')%>:</strong> <%= @proponent_presenter.city %></p>
            <p class="card-text"><strong><%= t('activemodel.attributes.proponent_form.state')%>:</strong> <%= @proponent_presenter.state %></p>
            <p class="card-text"><strong><%= t('activemodel.attributes.proponent_form.zip_code')%>:</strong> <%= @proponent_presenter.zip_code %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="row">
    <% @proponent_presenter.phones.each do |phone| %>
      <div class="col-md-6">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"><%= t(".labels.#{phone.phone_type}_phone") %></h5>
            <p class="card-text">
              <strong><%= t('activerecord.attributes.phone.number') %>:</strong>
              <%= phone.number %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <%= link_to t('.buttons.back'), proponents_path, class: 'btn btn-secondary border-0 rounded-pill shadow p-3 m-3' %>
</div>